# Generated by Django 4.2.16 on 2024-10-11 02:32

import DigiApp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DigiApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documento',
            name='archivo',
            field=models.FileField(upload_to=DigiApp.models.custom_filename),
        ),
    ]
