# Generated by Django 4.2.16 on 2024-10-11 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DigiApp', '0002_alter_documento_archivo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='documento',
            name='tags',
            field=models.ManyToManyField(related_name='documentos', to='DigiApp.tag'),
        ),
    ]
